# -*- coding: utf-8 -*-
"""AI-powered paraphrasing tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_gkne3XkxtXvlCSOmJGuDOzBfCZYAeW2

# 1. Introduction / Objective

Natural Language Processing (NLP) is a key area of Artificial Intelligence that focuses on enabling machines to understand and manipulate human language. One important application of NLP is paraphrasing, which involves rewriting text in a different form while preserving its original meaning.

The objective of this project is to develop an AI-powered paraphrasing system using transformer-based deep learning models. The system takes input text and generates a paraphrased version that maintains semantic meaning while improving clarity and readability.

In this implementation, a transformer model is used via the Hugging Face Transformers library to perform paraphrasing. Additionally, the system integrates grammar and spelling checks to ensure that the generated output is fluent and grammatically correct.

The project also includes evaluation of the generated outputs using similarity metrics to analyze how well the meaning is preserved. Through this approach, the project demonstrates both the capabilities and limitations of lightweight transformer models in real-world NLP applications.
"""

!pip install transformers==4.41.2 sentencepiece -q

from transformers import pipeline

paraphraser = pipeline("text2text-generation", model="google/flan-t5-small")

print("Model loaded correctly!")

"""# 2. Model Selection and Loading

In this project, the **FLAN-T5 small** transformer model was selected for the paraphrasing task.

### Why FLAN-T5 Small?

FLAN-T5 is an instruction-tuned version of the T5 (Text-to-Text Transfer Transformer) model. It is designed to understand and perform tasks based on natural language instructions such as "Paraphrase:" or "Rewrite this sentence".

The following reasons justify the selection of this model:

- **Instruction-based Learning:**  
  FLAN-T5 performs well on tasks like paraphrasing when given clear prompts, making it suitable for this application.

- **Lightweight and Efficient:**  
  The "small" version requires less computational power and memory, making it ideal for execution in environments such as Jupyter Notebook and Google Colab.

- **Ease of Integration:**  
  It can be easily implemented using the Hugging Face Transformers library without requiring complex fine-tuning.

### Why Not Other Models?

Other transformer models were considered but not used for the following reasons:

- **Large Models (e.g., larger T5 variants):**  
  Require high computational resources and may cause memory issues or slow performance.

- **API-based Models (e.g., GPT via external APIs):**  
  Require API keys and internet dependency, which may not align with the requirement of a self-contained console-based application.

- **Traditional Models (e.g., basic NLP techniques):**  
  Do not provide the same level of contextual understanding and paraphrasing capability as transformer-based models.

### Model Loading

The model is loaded using the Hugging Face Transformers pipeline for text-to-text generation, enabling direct input-output transformation for paraphrasing tasks.
"""

# !pip install transformers==4.41.2 sentencepiece language-tool-python -q

from transformers import pipeline
import language_tool_python

# Load model
paraphraser = pipeline("text2text-generation", model="google/flan-t5-small")

# Grammar tool
tool = language_tool_python.LanguageTool('en-US')


# -------------------------------
# FINAL FUNCTION
# -------------------------------
def generate_paraphrase(text):
    result = paraphraser(
        "Paraphrase: " + text,
        max_length=120,
        do_sample=False   # stable + clean
    )

    return result[0]['generated_text']


# -------------------------------
# LONG SENTENCE TEST
# -------------------------------
text = """Artificial Intelligence is rapidly transforming multiple industries across the globe by enabling machines
to analyze large volumes of data, identify patterns, and make intelligent decisions with minimal human intervention."""

print("----- ORIGINAL TEXT -----")
print(text)

paraphrased = generate_paraphrase(text)

print("\n----- PARAPHRASED TEXT -----")
print(paraphrased)


# -------------------------------
# GRAMMAR CHECK
# -------------------------------
matches = tool.check(paraphrased)

print("\n----- GRAMMAR CHECK -----")

if len(matches) == 0:
    print("No issues found")
else:
    for m in matches:
        print(m)

corrected = language_tool_python.utils.correct(paraphrased, matches)

print("\n----- CORRECTED TEXT -----")
print(corrected)

"""# 3. MULTIPLE TEST CASES (GENERAL SENTENCES)

The paraphrasing system was evaluated using multiple general sentences to test its performance across different contexts.

### Example 1
- **Original:**  
The weather was extremely cold, so we decided to stay indoors all day.  
- **Paraphrased:**  
We decided to stay indoors all day.  

The model simplified the sentence by removing the reason and focusing only on the action, resulting in loss of some contextual information.

---

### Example 2
- **Original:**  
She completed her assignment early and submitted it before the deadline.  
- **Paraphrased:**  
She completed her assignment early and submitted it before the deadline.  

The output remained identical to the input, indicating that the model preserved the sentence without introducing variation.

---

### Example 3
- **Original:**  
The restaurant serves delicious food, but the service can sometimes be slow.  
- **Paraphrased:**  
The food is delicious, but the service can sometimes be slow.  

The model successfully rephrased part of the sentence while maintaining the original meaning.

---

### Grammar Check
For all examples, no grammar or spelling issues were detected. The corrected outputs remained unchanged, confirming that the generated text was grammatically accurate.
"""

# -------------------------------
# MULTIPLE TEST CASES (GENERAL SENTENCES)
# -------------------------------

test_sentences = [
    "The weather was extremely cold, so we decided to stay indoors all day.",

    "She completed her assignment early and submitted it before the deadline.",

    "The restaurant serves delicious food, but the service can sometimes be slow."
]

print("----- MULTIPLE TESTING -----\n")

for i, text in enumerate(test_sentences, 1):
    print(f"Example {i}")
    print("Original:", text)

    # Paraphrase
    paraphrased = generate_paraphrase(text)
    print("Paraphrased:", paraphrased)

    # Grammar check
    matches = tool.check(paraphrased)

    if len(matches) == 0:
        print("Grammar: No issues found")
    else:
        print("Grammar Issues:")
        for m in matches:
            print(m)

    # Corrected output
    corrected = language_tool_python.utils.correct(paraphrased, matches)
    print("Corrected:", corrected)

    print("\n" + "-"*50 + "\n")

"""#4. Grammar and Spelling Error Detection

To ensure the quality and correctness of the generated paraphrased text, a grammar and spelling checking mechanism is integrated into the system using the LanguageTool library.

### How Errors are Detected

The system uses a rule-based approach provided by the LanguageTool engine:

- The paraphrased text is passed to the grammar checking tool.
- The tool analyzes the sentence based on predefined linguistic rules, including grammar, punctuation, and spelling.
- It identifies errors such as:
  - Incorrect verb forms (e.g., "He go" instead of "He goes")
  - Subject-verb agreement issues
  - Incorrect tense usage
  - Missing punctuation (e.g., commas)
  - Spelling mistakes

### Error Identification Process

- The tool returns a list of detected issues called "matches".
- Each match contains:
  - The type of error
  - The position of the error in the sentence
  - A description of the issue
  - Suggested corrections

### Error Correction

- The detected issues are processed using a correction function.
- Suggested corrections are automatically applied to the paraphrased text.
- The final corrected output is displayed to ensure grammatical accuracy and fluency.

### Example

- **Input:**  
  She go to school everyday and don't likes homework.

- **Paraphrased Output:**  
  She doesn't like homework.

- **Correction Result:**  
  No errors detected, indicating that the system has successfully improved grammatical correctness.

### Summary

This approach ensures that the final output is not only semantically meaningful but also grammatically correct and fluent, enhancing the overall quality of the paraphrasing system.

# 5. Results Explanation (Grammar Correction Testing)

To evaluate the grammar correction capability of the system, sentences containing intentional grammatical errors were used as input.

### Example 1
- **Original:**  
She go to school everyday and don't likes homework.  
- **Paraphrased:**  
She doesn't like homework.  

The model simplified the sentence and corrected grammatical errors, resulting in a shorter and grammatically correct output.

---

### Example 2
- **Original:**  
The food was very delicious but the waiter were rude and slow.  
- **Paraphrased:**  
The food was very good but the waiter was rude and slow.  

The model corrected verb agreement ("were" → "was") and improved word choice ("delicious" → "good").  
The grammar checker identified a punctuation issue and corrected it:

- **Corrected:**  
The food was very good, but the waiter was rude and slow.

---

### Example 3
- **Original:**  
I has completed my work but I didn't submitted it yet.  
- **Paraphrased:**  
I haven't submitted it yet.  

The model corrected multiple grammatical errors and simplified the sentence while preserving its meaning.

---

### Summary
The system successfully corrected grammatical errors, improved sentence structure, and ensured fluency in all test cases.
"""

# -------------------------------
# TESTING WITH GRAMMAR ERRORS
# -------------------------------

test_sentences = [
    "She go to school everyday and don't likes homework.",

    "The food was very delicious but the waiter were rude and slow.",

    "I has completed my work but I didn't submitted it yet."
]

print("----- GRAMMAR ERROR TESTING -----\n")

for i, text in enumerate(test_sentences, 1):
    print(f"Example {i}")
    print("Original:", text)

    # Paraphrase
    paraphrased = generate_paraphrase(text)
    print("Paraphrased:", paraphrased)

    # Grammar check
    matches = tool.check(paraphrased)

    if len(matches) == 0:
        print("Grammar: No issues found")
    else:
        print("Grammar Issues:")
        for m in matches:
            print("-", m.message)

    # Corrected output
    corrected = language_tool_python.utils.correct(paraphrased, matches)
    print("Corrected:", corrected)

    print("\n" + "-"*50 + "\n")

"""#5. Code Explanation: User Input Console

A console-based input system is implemented to allow users to enter their own sentences for paraphrasing.

- The user provides input using the `input()` function.
- The entered text is processed by the paraphrasing model.
- The output is displayed along with grammar and spelling analysis.
- A corrected version of the sentence is also provided.

This feature makes the system interactive and demonstrates its practical usability in real-world scenarios.**bold text**

### 5.1 Results Explanation (User Input Testing)

The system was further evaluated using a console-based user input to demonstrate real-time paraphrasing capability.

- **User Input:**  
In this project, a paraphrasing system was developed using a transformer-based model.

- **Paraphrased Output:**  
A paraphrasing system was developed using a transformer-based model.

The model successfully restructured the sentence by removing the introductory phrase while preserving the core meaning.

- **Grammar Check:**  
No grammar or spelling issues were detected.

- **Corrected Text:**  
The corrected output remained unchanged, confirming that the generated text is grammatically accurate and fluent.

This demonstrates the system’s ability to handle dynamic user input and generate meaningful, well-structured output.
"""

# -------------------------------
# USER INPUT TEST (CONSOLE BASED)
# -------------------------------

user_text = input("Enter a sentence to paraphrase:\n")

if user_text.strip() == "":
    print("No input provided.")
else:
    print("\n----- ORIGINAL TEXT -----")
    print(user_text)

    # Paraphrase
    paraphrased = generate_paraphrase(user_text)

    print("\n----- PARAPHRASED TEXT -----")
    print(paraphrased)

    # Grammar check
    matches = tool.check(paraphrased)

    print("\n----- GRAMMAR CHECK -----")

    if len(matches) == 0:
        print("No grammar or spelling issues found.")
    else:
        for m in matches:
            print("-", m.message)

    # Corrected output
    corrected = language_tool_python.utils.correct(paraphrased, matches)

    print("\n----- CORRECTED TEXT -----")
    print(corrected)

"""#6. Evaluation Metrics

To evaluate the performance of the paraphrasing system, multiple metrics were used.

### BLEU and ROUGE Scores
The BLEU and ROUGE scores were observed to be very low. This is because the model significantly modifies or simplifies the original sentence, resulting in minimal word overlap.

###CASE 1. Semantic Similarity
To better evaluate meaning preservation, semantic similarity was calculated using TF-IDF vectorization and cosine similarity.

- **Original:**  
She go to school everyday and don't likes homework.

- **Paraphrased:**  
She doesn't like homework.

- **Semantic Similarity Score:** 0.2061  

The score indicates that the paraphrased sentence retains only part of the original meaning. While the main idea (disliking homework) is preserved, additional context (attending school daily) is lost.

### Overall Analysis
The evaluation shows that the model tends to simplify sentences rather than generate detailed paraphrases. This results in low lexical similarity but partial semantic preservation.

This highlights a key limitation of lightweight transformer models, where there is a trade-off between simplicity and completeness of meaning.
"""

# Install lightweight library
!pip install scikit-learn -q

# -------------------------------
# Imports
# -------------------------------
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# -------------------------------
# Example (use ONE case)
# -------------------------------
original = "She go to school everyday and don't likes homework."
paraphrased_text = "She doesn't like homework."

print("----- SEMANTIC SIMILARITY -----\n")

print("Original:", original)
print("Paraphrased:", paraphrased_text)

# -------------------------------
# TF-IDF Vectorization
# -------------------------------
vectorizer = TfidfVectorizer()

vectors = vectorizer.fit_transform([original, paraphrased_text])

# -------------------------------
# Cosine Similarity
# -------------------------------
similarity = cosine_similarity(vectors[0], vectors[1])

print(f"\nSemantic Similarity Score: {similarity[0][0]:.4f}")

"""### CASE 2.  Additional Semantic Similarity Evaluation

A second test case was evaluated to analyze the model's performance on a well-structured paraphrase.

- **Original:**  
The restaurant serves delicious food, but the service can sometimes be slow.

- **Paraphrased:**  
The food is delicious, but the service can sometimes be slow.

The semantic similarity score was higher compared to the previous example, indicating that the paraphrased sentence preserved both structure and meaning effectively.

This demonstrates that the model performs better when minimal structural changes are required.
"""

# -------------------------------
# NEW TEST CASE (FROM YOUR PROJECT)
# -------------------------------

original = "The restaurant serves delicious food, but the service can sometimes be slow."
paraphrased_text = "The food is delicious, but the service can sometimes be slow."

print("----- SEMANTIC SIMILARITY (CASE 2) -----\n")

print("Original:", original)
print("Paraphrased:", paraphrased_text)

# -------------------------------
# TF-IDF + Cosine Similarity
# -------------------------------
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([original, paraphrased_text])

similarity = cosine_similarity(vectors[0], vectors[1])

print(f"\nSemantic Similarity Score: {similarity[0][0]:.4f}")

"""### Case 3: Sentence Simplification with Meaning Preservation

- **Original:**  
In this project, a paraphrasing system was developed using a transformer-based model.

- **Paraphrased:**  
A paraphrasing system was developed using a transformer-based model.

- **Semantic Similarity Score:** 0.7579  

The similarity score is relatively high, indicating that the paraphrased sentence preserves the core meaning of the original text.

The model removes the introductory phrase ("In this project") and simplifies the sentence while maintaining its essential information.

This demonstrates the model’s ability to generate concise and meaningful paraphrases without significantly altering the intended message.
"""

# -------------------------------
# FINAL CASE 3 (FROM SAMPLE)
# -------------------------------

original = "In this project, a paraphrasing system was developed using a transformer-based model."
paraphrased_text = "A paraphrasing system was developed using a transformer-based model."

print("----- FINAL CASE 3 -----\n")

print("Original:", original)
print("Paraphrased:", paraphrased_text)

# -------------------------------
# SEMANTIC SIMILARITY
# -------------------------------
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([original, paraphrased_text])

similarity = cosine_similarity(vectors[0], vectors[1])

print(f"\nSemantic Similarity Score: {similarity[0][0]:.4f}")

"""# 7. Challenges Faced

During the development of the paraphrasing system, several practical and technical challenges were encountered.

### Initial Model Selection Issues

The project initially started with the T5-small model for paraphrasing. However, the model often produced outputs that were identical to the input or showed very minimal variation. This limited its effectiveness in generating meaningful paraphrases.

To improve performance, the model was switched to FLAN-T5 small, which is an instruction-tuned version of T5. This change resulted in better handling of prompts and slightly improved paraphrasing quality.

---

### Model Output Limitations

Even after switching models, the paraphrased outputs were sometimes:
- Too similar to the original text
- Overly simplified, leading to loss of context
- Inconsistent in structure for complex sentences

This highlighted the limitation of lightweight transformer models in generating highly diverse paraphrases.

---

### Dependency and Environment Issues

While integrating additional features such as evaluation metrics, several dependency conflicts occurred:
- Errors related to incompatible versions of libraries (e.g., transformers and sentence-transformers)
- Import errors that disrupted the execution of the notebook

These issues required multiple environment resets and careful selection of lightweight libraries to ensure stability.

---

### Kernel Crashes and Memory Constraints

During experimentation with different models and libraries, the Jupyter/Colab kernel occasionally crashed or stopped responding. This was mainly due to:
- High memory usage by transformer models
- Loading multiple large libraries simultaneously

As a result, lightweight models and minimal dependencies were preferred to maintain smooth execution.

---

### Choice of Development Environment

Although Jupyter Notebook was initially considered, running complex transformer models locally caused instability and performance issues. Therefore, Google Colab was used as the primary environment due to:
- Better resource availability (RAM and GPU support)
- Easier package management
- Improved execution stability

---

### Evaluation Challenges

Implementing evaluation metrics such as BLEU and ROUGE presented challenges:
- Some metrics produced very low scores due to structural differences in paraphrased text
- Advanced semantic similarity libraries caused compatibility issues

To address this, simpler and more stable evaluation methods were adopted.

---

### Summary

These challenges highlight the practical difficulties of working with NLP models, including model limitations, environment setup issues, and dependency management. Overcoming these challenges required careful model selection, simplification of the approach, and iterative testing.

# 8. Conclusion

In this project, an AI-powered paraphrasing system was successfully developed using a transformer-based model. The system is capable of taking input text and generating paraphrased output while preserving the core meaning and ensuring grammatical correctness.

The implementation demonstrates how modern NLP techniques, particularly transformer models such as FLAN-T5, can be applied to real-world language processing tasks. The integration of grammar and spelling checking further enhances the quality and readability of the generated output.

Through multiple test cases, including normal sentences, grammatically incorrect inputs, and user-provided text, the system was evaluated for both accuracy and robustness. The results show that the model performs well in maintaining semantic meaning, especially for well-structured sentences, while also highlighting limitations such as reduced variation and occasional loss of contextual details.

Semantic similarity was used as the primary evaluation metric to measure how well the meaning of the original sentence is retained in the paraphrased output. The results indicate that the model achieves higher similarity scores for well-structured inputs and lower scores when significant simplification occurs.

Overall, the project effectively demonstrates the practical application of deep learning in Natural Language Processing. It also provides insights into the strengths and limitations of lightweight transformer models, making it a valuable learning experience in building real-world AI systems.
"""